stages:
  - test

test:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    # install dependencies
    - npm ci
    # Run & Record Cypress tests (DASHBOARD)
    - npx cypress run --record --parallel --browser chrome --key 0ba5e4b5-980b-48ae-b296-fb2da0f39eb3
    # Automate tests in Browserstack
    - browserstack-cypress run --sync
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day